[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist/frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "https://git-actions-tzjx.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
