name: Validate Folder Structure

on:
  pull_request:
    branches:
      - development-notes

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Check folders
        run: node scripts/check-folders.js
